### ISSUE TITLE
^@^@^@ added to the end of the file

### ISSUE THREAD

**Issue by chranmat** [klauspost/reedsolomon#100]
Hi,

I recently downloaded this library and started to test the examples attached in the examples/ folder.

When decoding a random text file I experienced that a string ^@^@^@ is added to the end of the decoded file.

Steps to reproduce:
1. Create a text file with some content. (Mark! Several newlines is used between the text in this file)
<img width="1445" alt="1" src="https://user-images.githubusercontent.com/18611032/57200309-c2730a80-6f8a-11e9-9ec9-61d4f4b2c418.png">

2. Use "simple-encoder" to encode the file in to 6 shards (default 4+2):
<img width="1445" alt="2" src="https://user-images.githubusercontent.com/18611032/57200323-e0406f80-6f8a-11e9-8fb9-c804e3c92b8c.png">

3. Delete the original file and 2 of 6 encoded shards
<img width="1445" alt="3" src="https://user-images.githubusercontent.com/18611032/57200328-efbfb880-6f8a-11e9-9911-29a931737fca.png">

4. Decode the remaining shards with "simple-decoder" (default 4+2)
<img width="1445" alt="4" src="https://user-images.githubusercontent.com/18611032/57200344-14b42b80-6f8b-11e9-8d90-807e948fec12.png">

Expected Result:
File is recovered in the original state

Actual Result:
The string ^@^@^@ is added on separate linje in the end of the file.
<img width="1445" alt="AR" src="https://user-images.githubusercontent.com/18611032/57200375-87bda200-6f8b-11e9-865d-bf435d7cfe97.png">

Additional info:
When using another example text with more content and less newlines this does not happen.

This picture is from when using the exact same method to reproduce, but different content:
<img width="1445" alt="ER" src="https://user-images.githubusercontent.com/18611032/57200440-6b6e3500-6f8c-11e9-9452-fadb86d4f8ac.png">

**Comment by chranmat** [comment]
Attached is also original and decoded file that reproduces the issue:

Original:
[file.original.txt](https://github.com/klauspost/reedsolomon/files/3146062/file.original.txt)

Decoded:
[file.decided.txt](https://github.com/klauspost/reedsolomon/files/3146064/file.decided.txt)

**Comment by raspi** [comment]
https://github.com/klauspost/reedsolomon#splittingjoining-data

> An important thing to note is that you have to **keep track of the exact input size**. **If the size of the input isn't divisible by the number of data shards, extra zeros will be inserted in the last shard**.

**Comment by klauspost** [comment]
See https://github.com/klauspost/reedsolomon/tree/master/examples#shortcomings
