### ISSUE TITLE
use intel isa-l or avx2 instructions

### ISSUE THREAD

**Issue by vtolstov** [klauspost/reedsolomon#11]
Thanks for this library, do you try to compare this package with intel isa-l (it already provides fast calculation and as i know erasure coding).
Also as i understand isa-l use non only sse3, but avx/avx2 if it available. Do you plan to support this optimization?

**Comment by klauspost** [comment]
Unless they use another technique, I believe a speedup would require AVX2. AVX only has the benefit is 3-op instructions, and we aren't  heavily burdened by register allocation - memory fetching is far dominant.

I don't have an AVX2 capable machine, so I haven't explored it.

`VPSHUFB ymm, ymm, ymm` can process twice the data that `PSHUFB xmm, xmm` can do, so we can maybe get a 20% speedup overall from AVX2 when considering memory latency, etc.

If you have an AVX2 machine we could use for testing?

**Comment by vtolstov** [comment]
yes, i'm have avx2, also i can provide vm for test that pass host cpu flags. If you send me email i can send credentials for this vm.

**Comment by vtolstov** [comment]
Thanks!
