### ISSUE TITLE
NEON support for ARMv7

### ISSUE THREAD

**Issue by jeffpeng78** [klauspost/reedsolomon#111]
Really loves this project and the performance is great on ARM64 NEON.

I am working on a project on the ARMv7 platform.
It looks like NEON is also supported on ARMv7:
[SIMD ISAs | Neon](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon)

Do you have any plan to support ARMv7 platform?
Thanks!

**Comment by klauspost** [comment]
No, but contributions are of course welcome.
