### ISSUE TITLE
linux arm64 build error

### ISSUE THREAD

**Issue by IoTServ** [klauspost/reedsolomon#125]
https://travis-ci.com/github/OpenIoTHub/server-go/jobs/327449253#L649
   ⨯ release failed after 384.08s error=failed to build for linux_arm64: # github.com/klauspost/reedsolomon
../../../../pkg/mod/github.com/klauspost/reedsolomon@v1.9.5/reedsolomon.go:464:4: r.codeSomeShardsAvx512P undefined (type reedSolomon has no field or method codeSomeShardsAvx512P)

**Comment by klauspost** [comment]
Thanks! I will see if I can find some better way to handle that.

**Comment by klauspost** [comment]
@IoTServ Thanks for reporting. I cleaned up the build tags a bit and I will try to set up some cross compilation to check for this.
