### ISSUE TITLE
File size not equal after decoding on Mac OS X

### ISSUE THREAD

**Issue by buaazp** [klauspost/reedsolomon#14]
Hi @klauspost 

I test the examples on my macbook, and the new file after decoding is bigger than the original. About 1~3 bytes bigger. Then I test the same case on Linux, the size is equal.

Maybe your asm codes are not compatible for OSX?

**Comment by klauspost** [comment]
Your input size must be dividable by the data shard count.

https://godoc.org/github.com/klauspost/reedsolomon#Encoder

See Split:
```Go
    // The data will be split into equally sized shards.
    // If the data size isn't dividable by the number of shards,
    // the last shard will contain extra zeros.
```

This is why you must specify the expected size when joining shards.

**Comment by buaazp** [comment]
I use your [examples](https://github.com/klauspost/reedsolomon/tree/master/examples) for testing. Not the library. All args use default value. And the tests on Linux is OK.

**Comment by klauspost** [comment]
See: https://github.com/klauspost/reedsolomon/blob/master/examples/simple-decoder.go#L14

```Go
// * If the file size of the input isn't diviable by the number of data shards
//   the output will contain extra zeroes
```

**Comment by buaazp** [comment]
I know the reason of Padding Bytes. Maybe you don't understand my issue.

step 1. my original file:
```
ls -l fangao.jpg
-rw-r--r--  1 zippo  staff  45835013  2 17 12:15 fangao.jpg
```
step 2. encode with your simple-encoder:
```
./simple-encoder fangao.jpg
Opening fangao.jpg
File split into 6 data+parity shards with 11458754 bytes/shard.
Writing to fangao.jpg.0
Writing to fangao.jpg.1
Writing to fangao.jpg.2
Writing to fangao.jpg.3
Writing to fangao.jpg.4
Writing to fangao.jpg.5
```
step 3. decode with your simple-decoder:
```
./simple-decoder -out a.jpg fangao.jpg
Opening fangao.jpg.0
Opening fangao.jpg.1
Opening fangao.jpg.2
Opening fangao.jpg.3
Opening fangao.jpg.4
Opening fangao.jpg.5
No reconstruction needed
Writing data to a.jpg
```
step 4. the new file is bigger:
```
ls -l a.jpg
-rw-r--r--  1 zippo  staff  45835016  2 17 12:15 a.jpg
```

And I'm confused that why this situation doesn't happen on Linux.

**Comment by buaazp** [comment]
Sorry, I got it. And I found the issue on Linux also.

**Comment by klauspost** [comment]
Glad you got the same results :)
