### ISSUE TITLE
Wrong reconstruct result

### ISSUE THREAD

**Issue by gopricy** [klauspost/reedsolomon#148]
Hi, I tested this package and it seems like the reconstructed shards is wrong
Here is my test
https://play.golang.org/p/sdgkOllg9eS

Let me know if I have some misunderstanding. Thanks!

**Comment by klauspost** [comment]
You never encode the shards. Split only splits the data, it does not encode the parity shards.

I didn't want to deal with your homemade Join, so I switched it to the original.

https://play.golang.org/p/AFiu79CROov
