### ISSUE TITLE
Benchmarks are wrong as you're testing very small chunks

### ISSUE THREAD

**Issue by vitalif** [klauspost/reedsolomon#158]
Hi.
Your benchmark data is wrong because when you're testing 10kb chunks everything resides in cache and you get very high performance.
For example BenchmarkEncode5x2x1M = 14 GB/s on my laptop with GOMAXPROCS=1, but if I raise chunk size to 1G it becomes 5.5 GB/s. And if I set it to 10000 the result becomes 23.5 GB/s which is over the head :))
5.5 GB/s is still good of course, ISA-L gives something like 5.6 GB/s with the same test on 1 core.
But your numbers are slightly misleading :)

**Comment by klauspost** [comment]
That is why the data size is specified.

You need to consider your cache size and memory throughput yourself.

**Comment by klauspost** [comment]
Since you are encoding data you just prepared, it is very likely the data is in one or another cache.

**Comment by vitalif** [comment]
I don't think so, real-world applications aren't guaranteed to operate on the same small memory range over and over...

Anyway, the first perfomance table in README doesn't state that it's for really small chunks of data so numbers like 100 GB/s look pretty astonishing and I think misleading

**Comment by vitalif** [comment]
Oh, sorry, it states that it's for 1 MB chunks. OK then, can you please tell how did you get 100 GB/s?

**Comment by klauspost** [comment]
There is a benchmark in the package. Not at my computer right now, but Encode... 5x2x1MB or something like it.

**Comment by vitalif** [comment]
Yeah I run it with go test -test.bench=. -test.run=aaaa, the only thing I can't reproduce is the parallel benchmark, -test.cpu=8 and GOMAXPROCS=8 have no effect in my case, the process still only uses 1 core...

**Comment by klauspost** [comment]
@vitalif The numbers are from my AMD desktop, this is from my Intel laptop, 6 cores:

```
λ go test  -test.v -test.bench ^BenchmarkEncode5x2x1M$ -test.run=None -cpu=1,2,4,8,12
goos: windows
goarch: amd64
pkg: github.com/klauspost/reedsolomon
BenchmarkEncode5x2x1M
BenchmarkEncode5x2x1M               3081            342325 ns/op        21441.72 MB/s
BenchmarkEncode5x2x1M-2             6567            180422 ns/op        40682.52 MB/s
BenchmarkEncode5x2x1M-4            11814             94297 ns/op        77839.47 MB/s
BenchmarkEncode5x2x1M-8            13984             86297 ns/op        85055.64 MB/s
BenchmarkEncode5x2x1M-12           13006             93323 ns/op        78652.09 MB/s
PASS
ok      github.com/klauspost/reedsolomon        10.855s
```
Latest master.
