### ISSUE TITLE
Inversion cache leaking memory?

### ISSUE THREAD

**Issue by TomerElya** [klauspost/reedsolomon#159]
Hey! I'll start off and say that everything said here is nothing but an assumption/not verified yet supported by facts we've concluded during our attempt to solve our issue.
I'll make this as short as I possibly can; we're using the package inside our project which is meant to support high rates of data transmission.
What we're doing is as follows: we transfer files from one end to another, each file eventually to be reconstructed by reedsolomon using this package.
The way we do is we assign a suitable amount of shards and parity per each file and on the receiving end we grab these numbers and use a map to map a pair of shards & parity to an encoder. I.e. reuse encoders.
The problem is, when we reuse encoders, our memory constantly goes up until we reach out of memory. When we do not reuse and create a new encoder per each file we receive, our memory doesn't go up but stays still.
We're talking massive amounts of RAM caught up by this. Reaching up to 360GB RAM in less than an hour.
I would love to know if there's something we're missing, perhaps is it possible that our encoders hold the data of our matrices? Are the encoders stateless that they allow reuse or do they keep data stored after they're used?
Any help is appreciated

**Comment by klauspost** [comment]
@TomerElya Since there are several ways to use the package, could you post code that reproduces the problem?

**Comment by TomerElya** [comment]
```go
type encoderConfig struct {
    shards int
    parity int
}

type Encoders struct {
    encoders map[encoderConfig]reedsolomon.Encoder
    lock *sync.RWmutex
}

func (encs *Encoders) Get(shards, parity int)  reedsolomon.Encoder {
    config := encoderConfig{shards, parity}
    encs.lock.RLock()
    encoder, exists := encs.encoders[config]
    encs.lock.RUnlock()
    if exists {
        return encoder
    }
    return encs.createNonExisting(config)
}

func (encs *Encoders) createNonExisting(config encoderConfig) reedsolomon.Encoder {
    encoder, err := reedsolomon.New(config.shards, config.parity)
    panicOnErr(err)

    encs.lock.Lock()
    defer encs.lock.Unlock()

    exisiting, exist := encs.encoders[config]
    if exists {
        return existing
    }

    encs.encoders[config] = encoder
    return encoder
}
```

**And we use a reedsolomon encoder in both these cases:**
```go
func (s *ShardReconstructor) reconstruct() ([]byte, error) {
    enc := s.encs.Get(s.shards, s.parity)
    err := enc.ReconstructData(s.data)
    if err != nil {
        return nil, err
    }
    shardLen := 0
    for _, innerShard := range s.data {
        if len(innerShard) != 0 {
            shardLen = len(innerShard)
            break
        }
    }
    
    dataLen := s.shards * shardLen
    buf := make([]byte, 0, dataLen)
    w := bytes.NewBuffer(buf)

    err = enc.Join(w, s.data, dataLen)
    if err != nil {
        return nil, err
    }

    return w.Bytes(), nil
}
```

```go
func (r *ChunksReconstructor) reconstructData() ([]byte, error) {
    enc := s.encs.Get(s.shards, s.parity)
    err := enc.ReconstructData(s.data)
    if err != nil {
        return nil, err
    }
    
    dataLen := s.shards * len(r.data[0])
    buf := make([]byte, 0, dataLen)
    w := bytes.NewBuffer(buf)

    err = enc.Join(w, r.data, dataLen)
    if err != nil {
        return nil, err
    }

    return w.Bytes(), nil
}
```

**Comment by klauspost** [comment]
@TomerElya Do you have a working sample? None of the calls you are using are storing any state or have any huge buffers, so I would suspect the problem is elsewhere in your code.

**Comment by TomerElya** [comment]
@klauspost Generally, the reconstructed data is returned from the function and proceeds onto a different worker which writes the data and it ends here.
My problem resides exactly here. Once the data is written, I no longer hold any reference to it so we expect it to be garbage collected. I can not say what structure/object remains allocated that slowly takes up all of our memory yet I do know that if I don't reuse the encoders but create new instances for each incoming file, my memory stays still and doesn't flood.
Here I thought perhaps you could provide us with any leads on what could we possibly be doing wrong?

**Comment by klauspost** [comment]
@TomerElya If you cannot create a reproducer I am only guessing, and I don't expect the problem to be in the code you provided. 

The `encoder, err := reedsolomon.New(config.shards, config.parity)` is thrown away in a few cases, but should be collected. Move the New to when you know you need it. But unlikely that will fix it.

You can create a memory profile what will show you where the leaking data is being allocated with `inuse_space`. That should be able to tell you what is being kept around.

**Comment by TomerElya** [comment]
I'm unable to export my memory profile file out here but top5 shows the following:
2. ShardReconstructor.reconstruct:
 flat% 31.27%
 sum% 74.94%
 cum% 49.88%
3. klauspost/reedsolomon.newMatrix:
 flat% 16.57%
 sum% 91.51%
 cum% 16.57%
5. klauspost/reedsolomon.inversionNode.insertInvertedMatrix:
 flat% 1.88%
 sum% 97.85%
 cum% 1.88%

First spot is the function responsible for reading all the data from the file sender and then deliver it to the reconstructors, so I guess it makes sense for it to take the most memory.

Is it possible at all that the encoders hold any state at all? From previous reconstructions, buffers allocated for the decoding process?
I can't escape the fact that dumping used encoders and create new ones makes my memory leakage disappear

**Comment by klauspost** [comment]
It does cache inverted matrices so they don't have to be recalculated . 

This was contributed in #36

https://github.com/klauspost/reedsolomon/blob/c54154da9e35cab25232314cf69ab9d78447f9a5/inversion_tree.go#L26

I wouldn't really expect it to cause the memory usage you are describing. Maybe @somethingnew2-0 is still around?

I will see if I can figure something out, otherwise I will find a way to disable it.

**Comment by klauspost** [comment]
@TomerElya Could you try out #160 - both with the changes and if that alone doesn't help with `WithInversionCache(false)` as well?

**Comment by TomerElya** [comment]
@klauspost I have updated to #160 and ran it alone, same thing appeared to happen. I'm now running with AddInversionCache(false) and the memory seems steady. I'll let it run for a few hours or even overnight and hope for the best tomorrow.
I must say that I highly appreciate your fast response and care for our issue.

**Comment by klauspost** [comment]
Let me know. I will merge it either way.

**Comment by TomerElya** [comment]
@klauspost Held strong all night. Fixed our issue.

And, well, we move a pretty big amount of files and it seemed to have piled up with time until we got the OOM.

**Comment by klauspost** [comment]
Unless there is a big number (virtually any combination) of encoders created it shouldn't grow to the sizes you describe.

I will keep this open until I have the chance to check that it isn't spending more ram than it needs to.

**Comment by klauspost** [comment]
@TomerElya Could you give an estimate on the number of different `encoderConfig` variations and the ranges of the number of data/parity shards?

**Comment by TomerElya** [comment]
@klauspost By estimation, we didn't have more than 7-10 encoders tops. To test our system we used the same size for files which resulted in the same encoders being reused. As for amount of shards/parity, that really depends on the size of the files we sent since we have our own calculation to determine the amount of shards and parity we desire.

**Comment by klauspost** [comment]
@TomerElya What is the ballpark of total data+parity shards?

**Comment by TomerElya** [comment]
@klauspost A calculation we use that varies based of the value of multiple parameters. I really can't give an answer that will suffice or be accurate.
