### ISSUE TITLE
matrix is singular error

### ISSUE THREAD

**Issue by amits1995** [klauspost/reedsolomon#16]
Hi, I am using the example's files to test the code.
When I take a 100MB file with 250 data shards and 125 pairity shards and then delete shards 0-49 and 270-279 reconstruction fails with matrix is singular error. Is this suppose to happen? Cause I thought I can lose up to 125 shards and still recover the data.
What am I missing?
Thanks, Amit

**Comment by amits1995** [comment]
Also happens for random 40kb buffer and some other files. For fewer pairity/shards (e.g 50/20) error doesn't occur. Is the likelihood of singularity rises when the size of the matrix rises?

**Comment by xiaost** [comment]
it seems the  rows/cols idx exceeds byte len when generating Vandermonde matrix within Galois Field

https://github.com/klauspost/reedsolomon/blob/master/matrix.go#L271

**Comment by klauspost** [comment]
It would seem that to be safe from this the number of data+parity shards should not exceed 255.

I did some tests, which only seemed to fail if the number of data shards where >255, but it seems like there is another limitation that kicks in when reconstructing.

**Comment by amits1995** [comment]
Hi,
Thanks for the answer.
I think I missed the point of how to avoid this or that maybe it's a bug?
Are you saying that shards+parity cannot excced 255? Cause I didn't infer
that from the documentation. (And also there's no error for those
dimensions)
Sorry for my lack of understanding.

**Comment by klauspost** [comment]
>Are you saying that shards+parity cannot excced 255?

That would be my recommendation. I will do some more tests, but for now, I would stick to that.

**Comment by amits1995** [comment]
Thank you very much

**Comment by harshavardhana** [comment]
AFAIK - (k + m) cannot be bigger than Galois field GF(2^8) - 1

**Comment by amits1995** [comment]
ok so shouldn't we add a check at the constructor?

**Comment by klauspost** [comment]
That would make sense, yes -  as well as updating the documentation
