### ISSUE TITLE
Two zero valued bytes added to the end of decoded file

### ISSUE THREAD

**Issue by simonsben** [klauspost/reedsolomon#167]
I believe using three data and two parity (and potentially others) an additional two zero valued bytes are added to the end of the decoded file.

## Steps to reproduce

* Clone repo
* Create `test/` folder within [`examples/`](https://github.com/klauspost/reedsolomon/tree/master/examples)
* Encode file with `go run ../simple-encoder.go -data 3 -par 2 -out . ../README.md`
* Decode file with `go run ../simple-decoder.go -data 3 -par 2 -out test.md README.md`

The decoded file now has an additional zero byte at the end of the file. This can be seen using `hexedit test.md`

**Comment by klauspost** [comment]
https://github.com/klauspost/reedsolomon/blob/master/examples/simple-encoder.go#L15

**Comment by simonsben** [comment]
I see that its listed as a behavior, is it not worth correcting though?

**Comment by klauspost** [comment]
@simonsben The example is meant to be simple, not exhaustive. You are welcome to send an alternative.
