### ISSUE TITLE
Slice bounds out of range at ReconstructData

### ISSUE THREAD

**Issue by TomerElya** [klauspost/reedsolomon#183]
Hey. I’m getting a slice bounds out of range with capacity 0 at
galMulAVX512Parallel84 (galoisAvx512_amd64.go:194)

It only happens once in very very few, since everything runs smoothly and processes many matrices but after a while panics for one that catches this case and I can’t seem to understand what’s happening 
I’ll provide some code in a few
But there isn’t much to see since it’s a 116 shards matrix, 106 shards, 10 parity 

Would love some help, thanks!

**Comment by klauspost** [comment]
@TomerElya Please also post the crash trace.

**Comment by TomerElya** [comment]
Klauspost/reedsolomon.galMulAVX512Parallel84

klauspost/reedsolomon/galoisAvx512_amd64.go194

klauspost/reedsolomon.(*reedSolomon).codeSomeShardsAvx512

klauspost/reedsolomon/reedsolomon.go:513

klauspost/reedsolomon.(*reedSolomon).reconstruct

klauspost/reedsolomon/reedsolomon.go:885

klauspost/reedsolomon.(*reedSolomon).ReconstructData

**Comment by klauspost** [comment]
Thanks. I will take a look! 👍🏼

**Comment by klauspost** [comment]
@TomerElya Are you sure you aren't modifying the input `shards [][]byte` while it is processing?

The crash should be fully consistent unless you have a data race, where you are modifying the slice, for example by sharing a pointer to it in a pool.

**Comment by TomerElya** [comment]
I’ll double check and respond as soon as I can tell
Would any modification to the source array matter?

**Comment by klauspost** [comment]
@TomerElya Anything sent as parameters must remain untouched by other goroutines while the function is running.

**Comment by TomerElya** [comment]
You might have been right and I had an extreme edge case where I would assign to my [][]byte an additional shard during reconstruction 
Handling this might’ve solved the problem, but I’m making sure
@klauspost

**Comment by klauspost** [comment]
@TomerElya That could trigger it. Feel free to reopen with a reproducer.
