### ISSUE TITLE
replace [][]byte with []byte to reduce gogc scan time

### ISSUE THREAD

**Issue by yuanchao0310** [klauspost/reedsolomon#184]
if data stored in [][]byte, the pointer number is the length of [][]byte,
if data stored in []byte, there is only 1 pointer number, so it can reduce gogc scan objects time.
How do you think if use `Matrix{[]byte, row, col}` struct?

**Comment by klauspost** [comment]
Considering you are just dealing with max 256 entries I don't think that micro-optimization will bring any close to measurable difference.

**Comment by yuanchao0310** [comment]
Thanks for your quick reply.
I use reedsolomon on UDP packet, the udp data length range in (100-1400)
when my program start, I call reedsolomon.New(i, j) to create 256 Encoder (1<=i<=16, 1<=j<=16)and put these encoder object in lru.cache for future use.
each time I call Encode() or ReconstructData(), the input data length maybe different
for example:
encoder := GetCacheEncoder(16,4) // data shards length, parity shards length
encoder.ReconstructData(shards) // the input packet length maybe 100
encoder.ReconstructData(shards1) // the input packet length maybe 101
....
encoder.ReconstructData(shardsN) // the input packet length maybe 1400

encoder = GetCacheEncoder(16,8) // data shards length, parity shards length
encoder.ReconstructData(shards) // the input packet length maybe 100
encoder.ReconstructData(shards1) // the input packet length maybe 101
....
encoder.ReconstructData(shardsN) // the input packet length maybe 1400

form golang pprof result, `dataDecodeMatrix, err = subMatrix.Invert()` call `identityMatrix(size)` and `work.SubMatrix(0, size, size, size*2)` create many newMatrix()

**Comment by klauspost** [comment]
@yuanchao0310 I don't really see this being efficient in any reasonable way. 

How are you even determining which parts are good?

Sounds like you are looking for Hadamard,  LDPC or Turbocodes instead.

**Comment by yuanchao0310** [comment]
@klauspost I use reedsolomon in webrtc project.
I send audio/video data packets and send some parity shards according to the network detecting result(rtt, loss rate ...),
The audio/video packet length are different, so I use max length of a group packets.
From golang pprof result, reedsolomon inuse objects is only 2%.
Just ignore this issue, I need continue to improve my application layer code to reduce the inuse objects.
Thanks again for your reply.
