### ISSUE TITLE
Request to enable tests for windows

### ISSUE THREAD

**Issue by harshavardhana** [klauspost/reedsolomon#21]
This package should enable tests for windows using http://www.appveyor.com/ a sample appveyor.yml is here. 

```
$ cat appveyor.yml
# Operating system (build VM template)
os: Visual Studio 2015

platform: x64

clone_folder: c:\gopath\src\github.com\klauspost\reedsolomon

# environment variables
environment:
  GOPATH: c:\gopath

# scripts that run after cloning repository
install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rd C:\Go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.windows-amd64.zip
  - 7z x go1.6.windows-amd64.zip -oC:\ >nul
  - go version
  - go env
  - cd %GOPATH%\src\github.com\klauspost\reedsolomon

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go test .
  - go test -race .

# to disable automatic tests
test: off

# to disable deployment
deploy: off
```

**Comment by klauspost** [comment]
I am pretty sure that Appveyor has Go installed already. Maybe if you based it on this, it could be simplified a little: 

https://blog.klauspost.com/travisappveyor-ci-script-for-go/

**Comment by harshavardhana** [comment]
> I am pretty sure that Appveyor has Go installed already. Maybe if you based it on this, it could be simplified a little:
> 
> https://blog.klauspost.com/travisappveyor-ci-script-for-go/

Ah i see you wrote a nice blog,  the go installation is just to make sure we have latest version - they usually lag behind a bit.  Should i send a PR?

**Comment by klauspost** [comment]
I would prefer the pre-installed,  even if it is a bit old. That way we don't have to do manual updates. Travis should test the different Go versions anyway.
