### ISSUE TITLE
question / feature request: usage from python?

### ISSUE THREAD

**Issue by alekibango** [klauspost/reedsolomon#22]
I would love to use this library from my python application.
I am not really sure what would be the best way, as i never used golang before.

One possible method could be using zeromq as interface --  go binding is here:   https://github.com/pebbe/zmq4

This could make really good networked/ipc api, which might be used by all other platforms too.
Or is there a better way to use this from python?

**Comment by klauspost** [comment]
Thanks for the suggestion!

I don't think that belongs in a base package, but rather in a separate project. Unfortunately I don't currently have the time available to do so. Sorry about that, but I would rather be sure I could do a good job before committing to this.

I am not sure zeromq is the right way to go for any reasonable level of performance, but I would be happy to hear if you get any experiences with that.

**Comment by alekibango** [comment]
i cant speak for zeromq go bindings, but from other languages zeromq is pretty good in terms of performance and ease of use.  But yes, it takes some time to get used to it.
You can try reading http://zguide.zeromq.org/,  the book  is really good and funny read, even  if you will not use zeromq :)

If i get this right (just watched some go presentation) zmq can be used like 'go channels' sending messages over tcp/ipc.

Python wrapper for this go library would sure be a better  solution (at least for python users), but i am not sure how to make this well yet.

**Comment by jannson** [comment]
@alekibango Try a Cython bind to this project: https://github.com/klauspost/reedsolomon/issues/37 ?

**Comment by jcftang** [comment]
There is zfec and PyECLib for python if you need erasure coding, they may not be compatible with this implementation though.

**Comment by alekibango** [comment]
@jcftang: i have tried those, but they were much slower. 

Thansk for tips, guys! will give #37 a try.

**Comment by alekibango** [comment]
@jannson: Funny thing is that reedsolomon-c implementation is 3 times slower than this one written in go...  I am not sure why.
