### ISSUE TITLE
Encoder return the same content for many shards 

### ISSUE THREAD

**Issue by AT19947** [klauspost/reedsolomon#251]
I'm using the example https://github.com/klauspost/reedsolomon/blob/master/examples/simple-encoder.go to split a file into 24 shards (12 data & 12 parity). The output of the encoder is 24 files, 11 shards have the same content whereas the content of the file is not the same and it's not contain replicated data. This happens just for one file. I've tried other files and the issue has not happened.

**Comment by AT19947** [comment]
@klauspost please help

**Comment by klauspost** [comment]
Sounds a bit unlikely, but could you attach the file in question here?

You gzip it and drop it into this field. Also please provide the commandline you used.
