### ISSUE TITLE
`ReconstructSome` for Leopard

### ISSUE THREAD

**Issue by Wondertan** [klauspost/reedsolomon#264]
Like Couchy, Leopard needs `ReconstructSome` implementations s.t. consumers can avoid reconstructing unnecessary data. Currently, it falls back to regular [Reconstruct](https://github.com/klauspost/reedsolomon/blob/674f18bb1f8189237afb301da140a899a4a85756/leopard.go#L335). User's like Celestia currently have to recompute all the 128 shards when only single one is needed.

**Comment by klauspost** [comment]
See https://github.com/klauspost/reedsolomon/discussions/263

**Comment by Wondertan** [comment]
My bad

**Comment by Wondertan** [comment]
It feels like there is consensus over it, so it might need an actionable issue rather than a discussion.

**Comment by klauspost** [comment]
@Wondertan I do not keep issues for features/improvements.
