### ISSUE TITLE
Make join return an error if a reconstruction is required first - e.g. one or more data shards are nil

### ISSUE THREAD

**Issue by muesli** [klauspost/reedsolomon#33]
Less of an issue, more of a question:

If I feed Split with little data (say 4 bytes) and have more than 4 shards, there won't be an error returned, even though it'll break reconstructing the data later on.

Is this something you would consider the library handling internally or is this simply an invalid situation / use-case?

**Comment by klauspost** [comment]
How does it fail? After #20, it should just be zero padded.

**Comment by muesli** [comment]
I think I see what's happening now and I probably misunderstood the API a bit. I was under the assumption that Join() would return an error if reconstruction was required before joining (e.g. one of the shards is nil) is possible. Instead it happily decodes invalid data (starting with the first nil shard), which didn't match my input data - obviously.

I'll update the title and let you decide what you consider correct behaviour :-)

**Comment by muesli** [comment]
I'll happily send in a pull request should that indeed be the desired behaviour.

**Comment by klauspost** [comment]
I would appreciate that. Be mindful of current usage of the behavior, so we don't create problems for people, where the current behavior makes sense. It should detect "holes" in input, where len(shard n) > len(shard-1), which would be safe to assume is an error AFAICT. Please create a unique exported error, so it can be caught by package users.
