### ISSUE TITLE
Allow 0 parity shards

### ISSUE THREAD

**Issue by drorbar** [klauspost/reedsolomon#35]
Although it doesn't allow a way to reconstruct the data, I think it should be allowed to pass 0 parity shards to the code.
First, it doesn't "harm" the code, it would still work, but will require that every dataShard is still intact - which in my opinion is ok.
Second, right now if a program use the library, and for some "input type" it should use parity and for some it shouldn't, it required from the programmer to write entire section dealing with 0 parity which would do the same as the library.

Am I missing something basic about the library or is it simple as removing the "if" in file reedsolomon.go(line 107)

**Comment by muesli** [comment]
I must admit I ran exactly in that situation myself, too. While it's not hard to write your own join/split, it would be rather convenient to have it all handled by one lib & code-path.

**Comment by klauspost** [comment]
@JackSparrow94 If you have tests that verify that the other functions work with 0 parity shards, I would not mind loosening this requirement.

**Comment by JackSparrow94** [comment]
Will try to add those tests to the ones already exists and make sure nothing breaks

**Comment by JackSparrow94** [comment]
Tests on reedsoloon_test.go passed without a problem is there a reason to check streaming? I didn't used this in my code so I not sure what the streaming do

**Comment by vtolstov** [comment]
@klauspost please, review this pr, i want to use parity 0 in case i don't need additional data to reconstruct. This is simplify code that uses this library.

**Comment by klauspost** [comment]
@vtolstov - there is no PR. You are welcome to send one in if you have the time.
