### ISSUE TITLE
C compatible version support

### ISSUE THREAD

**Issue by jannson** [klauspost/reedsolomon#37]
This is a great repo, and I have use it in my personal project.
Then I implement a compatible C version here: https://github.com/jannson/reedsolomon-c
Only one .c file, you can just copy it to your project.

I will make more test later. if someone like it, please have a try :)

**Comment by klauspost** [comment]
Cool. I have added a link in the link section!

**Comment by jannson** [comment]
Thanks. I will add more document, and write some test tools to prove that it's really compatible with you golang version.

**Comment by jannson** [comment]
1. unit test ok
2. document ok
3. compatible tool test ok
4. benchmark not ok

Now I want  to close this issue  :)

**Comment by klauspost** [comment]
Very nice!
