### ISSUE TITLE
On codeSomeShardsP

### ISSUE THREAD

**Issue by xtaci** [klauspost/reedsolomon#38]
```go
	if runtime.GOMAXPROCS(0) > 1 && len(inputs[0]) > minSplitSize {
		r.codeSomeShardsP(matrixRows, inputs, outputs, outputCount, byteCount)
		return
	}
```

I think we need some options to disable(or tune) this, under heavy work, more computational goroutines won't bring performance boosts, or even worse.

how do you think about this?

**Comment by klauspost** [comment]
Sounds like a good change. To make it the most flexible it should probably be a function on the "Encoder"/"StreamEncoder" interfaces, however I am not a huge fan of adding function to existing interfaces.

What do you see as the best way of adding this?

**Comment by xtaci** [comment]
for the moment, the best way is by adding ```func SetParallel(num int)``` to reedSolomon struct.

**Comment by xtaci** [comment]
besides, I'm porting a C++ version of reedsolomon for mobile devices, almost complete.
https://github.com/xtaci/libkcp,  looking forward to your help.

**Comment by klauspost** [comment]
I have made this configurable through #46 - does that make sense for you?
