### ISSUE TITLE
Export the `reedSolomon` struct

### ISSUE THREAD

**Issue by meling** [klauspost/reedsolomon#40]
I believe a more idiomatic Go approach would be to make the `reedSolomon` struct exported, e.g. by renaming it to `ReedSolomon`. Then the `New()` function should also be changed to return `*ReedSolomon`, making the already capitalized fields of this struct visible to its users. 

As it is now, these fields (`DataShards`, `ParityShards`, `Shards`) are not visible because `New` returns an `Encoder` interface, and this causes me to have to store these same values also in my own struct, because I can't access the fields of the `reedSolomon` struct.

I've implemented this change locally, and I'd be happy to provide a pull request (pending a response to this issue). It requires three minor additional changes (essentially avoiding a few type assertions), but I believe this change is non-breaking, since the returned `*ReedSolomon` object will implement the `Encoder` interface. The tests still pass after my change.

**Comment by klauspost** [comment]
I don't believe it is more idiomatic. If you have some specifics, feel free to share.

Exporting an interface makes it possible to have alternative implementations with the same or similar interface. Furthermore it hides implementation details and allows them to be changed without breaking the API. Lastly changing from interface to struct can potentially break existing applications.

I would probably approve adding a function that returns a struct with information about your encoder settings.

**Comment by meling** [comment]
Sorry, I shouldn't have claimed idiomaticity without any references, and I don't even know if these sources are authoritative in that respect, but I find them compelling: 

https://medium.com/@cep21/preemptive-interface-anti-pattern-in-go-54c18ac0668a#.e6gkaujxp
https://medium.com/@cep21/what-accept-interfaces-return-structs-means-in-go-2fe879e25ee8#.x6a4ijcrt

Dave Cheney referred to the following quote in his SOLID talk/blog:
```
A great rule of thumb for Go is accept interfaces, return structs.
                                                  –Jack Lindamood
```

A relevant use case for returning an interface can be found here: 

https://golang.org/doc/effective_go.html#generality

However, given that the number of methods in the `Encoder` interface are so many, it seems unlikely that this interface would serve this generality purpose IMO. To that end, it feels like the `Encoder` interface could have been decomposed into two separate interfaces: Encoder and Decoder, although I've not given that much thought... (it's clearly more intrusive than changing the return type to a struct). But if you do return a struct that implements both, you can restrict your own use to one of the two interfaces.

You mention adding a function. Do you mean to add a method to the Encoder interface to return the encoder settings? I can't think of another way to do it, unless you mean to add another `NewEncoder()` method (or something) that actually returns a struct.

Finally, do you have an example of how changing it to a struct instead of interface would break existing applications?

**Comment by klauspost** [comment]
Fair point. I think you however missed my point about this being a breaking change.

I will not change the API based on neatness. If you were solving a fundamental issue, of course but not for exposing two variables.

**Comment by lukechampine** [comment]
@klauspost there is a performance reason to export `reedSolomon`. Because `Encoder` is an interface, the compiler cannot perform escape analysis on the underlying type. For example, when you call `Encode(shards)`, the compiler is forced to move `shards` to the heap because it cannot prove that `Encode` does not retain a pointer to `shards`.

Returning `*ReedSolomon` from `New` would be ideal, but as you said, that is a breaking change. Instead, I propose simply exporting the type. That way, callers can write:
```go
enc, _ := reedsolomon.New(m, n)
rs := enc.(*reedsolomon.ReedSolomon)
```
The compiler will then be able to do proper escape analysis on `ReedSolomon` instead of `Encoder`.
