### ISSUE TITLE
Why return both bool and error from Verify()?

### ISSUE THREAD

**Issue by meling** [klauspost/reedsolomon#42]
It seems a little burdensome to deal with both error and bool from `Verify()`. It seems to me to be an easy fix to make it just return an error. A correct verification would return nil. 

Just curious if this something that is needed in its current form. And if you consider such a breaking change unacceptable because of some compatibility promise (or large active user base that depend on the current API)?

**Comment by klauspost** [comment]
It saves the caller the trouble of having to inspect the returned error to see if it was invalid parameters passed, or the verification actually failed.
