### ISSUE TITLE
Unavoidable allocation in Reconstruct

### ISSUE THREAD

**Issue by lukechampine** [klauspost/reedsolomon#43]
My understanding of the `Reconstruct` function is this: For missing shards, the caller passes `nil`. Inside `Reconstruct`, a new slice is allocated for each missing shard, and the reconstructed data is copied into it.

The problem is that there is no way to reuse existing memory here; `Reconstruct` will _always_ allocate a new slice for each missing shard. This can get costly if you are missing many pieces and making frequent calls to `Reconstruct`. In [Sia](https://github.com/NebulousLabs/Sia), we store files using a 0.5MB shard size and only download the minimum number of shards. Since our code is 8 data/24 parity, that means `Reconstruct` will allocate 24*0.5 = 12MB for each 4MB we download.

Is there any way to avoid these allocations? Passing a pre-allocated slice doesn't work because `Reconstruct` has no way to distinguish it from real data, but perhaps we could pass a slice with `len == 0` and `cap == shardSize`. I can PR this if you feel it's a good approach.

**Comment by klauspost** [comment]
That does seem like an acceptable solution, the chance of this colliding with existing functionality is very, very small. If it is possible for you to cook up a PR that would be greatly appreciated.

**Comment by klauspost** [comment]
Fixed through #66 - thanks for reporting.
