### ISSUE TITLE
The current v1.3 git tag is lightweight; please make it into an annotated tag

### ISSUE THREAD

**Issue by henti** [klauspost/reedsolomon#48]
Hi @klauspost,

While packaging reedsolomon for Debian, I received an error from `dh-make-golang` tool (https://github.com/Debian/dh-make-golang) that you are using lightweight tags. 

This can be problematic as amongst other things, they are ignored by "git describe" by default.

if you'd like more details on the problem, see this bug report for details: 
https://github.com/russross/blackfriday/issues/196

**Comment by klauspost** [comment]
If this is a common problem, why not fix your tool?

I have no idea what you are asking me to do. Is there a way to do this in the Github releases section?

**Comment by henti** [comment]
Hi Klaus, 

dh-make-golang, which is part of Debian, only highlighted the problem. There is many arguments on the merits of each, but simply put, annotated tags records knowing who tagged the release and when. This is not true of lightweight tags. 

The former makes packaging your code for wide distribution easy to automate, the latter does not. 

More information on working with tags in github can be found here: 
https://help.github.com/articles/about-releases/
