### ISSUE TITLE
Benchmark code?

### ISSUE THREAD

**Issue by spikebike** [klauspost/reedsolomon#6]
I was interested in the benchmarks you posted in the README.md.  I wanted to compare to other approaches.  But I didn't see the code for the (5,2), (10,2), (10,4), (50,20), and 1,2,4 and 8 thread runs.  Did I miss it?   

For scaling was that inside the enc.Encode?  Or interleaving enc.split across multiple encodes?

**Comment by klauspost** [comment]
It is in [reedsolomon_test.go](https://github.com/klauspost/reedsolomon/blob/master/reedsolomon_test.go#L218)

To run the ones you mention:
```bash
go test -bench=Encode5x2x1M -cpu=2
go test -bench=Encode10x2x1M -cpu=2
go test -bench=Encode10x4x1M -cpu=2
go test -bench=Encode50x20x1M -cpu=2

go test -bench=Encode10x4x16M -cpu=1,2,4,8
```

Slices are calculated 512 bytes at the time in parallel goroutines. See https://github.com/klauspost/reedsolomon/blob/master/reedsolomon.go#L223

**Comment by spikebike** [comment]
Great, perfect, thanks.
