### ISSUE TITLE
Reconstruct should consider shard buffer capacity

### ISSUE THREAD

**Issue by aead** [klauspost/reedsolomon#67]
Currently [reconstruct data](https://github.com/klauspost/reedsolomon/blob/master/reedsolomon.go#L685) and [reconstruct parity](https://github.com/klauspost/reedsolomon/blob/master/reedsolomon.go#L707) allocate a new shard when the shard is marked as missing (`len(shard) == 0`).
Reconstruct should check whether the capacity of the shard is large enough to avoid the allocation whenever possible.

**Comment by klauspost** [comment]
Fixed. Thanks for the report
