### ISSUE TITLE
PAR2 Creation

### ISSUE THREAD

**Issue by Fossil01** [klauspost/reedsolomon#72]
I've tried to find one but is there a project which uses this repo to create PAR2 files? I've been looking for a faster alternative to https://github.com/animetosho/ParPar.

**Comment by klauspost** [comment]
PAR2 uses gf16 for up to 65535 blocks. The current library only has an gf8 implementation.

I am interested in a gf16 engine, but currently does not have the resources to write it.

**Comment by darrenldl** [comment]
Is gf16 used very commonly in places other than PAR2? Or is there a very practical reason to prefer gf16 over gf8?

I am somewhat interested in adding this to the Rust port, but I can't seem to find many software/designs that use gf16.

**Comment by let4be** [comment]
Has someone managed to verify/repair par2 using this library? Is there anything implementing gf16 in go?
Thanks

**Comment by Joshfindit** [comment]
I feel like this is probably out of scope for the project, but I've been hoping someone can pick up the ideals from the now-dusty PAR2 tools in a way that can be used on USB sticks, in home labs, and on personal/SMB servers.

*(I also wouldn't mind if someone tacked on subfolder support to PAR2 files by storing relative path in the index, but that's just for future Googlers who come across this project)*

**Comment by animetosho** [comment]
I'm not sure what you mean by "can be used on USB sticks [etc]", but PAR2 supports subfolders just fine, from what I can tell.

**Comment by klauspost** [comment]
GF16 has been added, but not a PAR 2 compatible one.

I do not plan to add another since it will be interior.
