### ISSUE TITLE
build have this error!

### ISSUE THREAD

**Issue by Hoke** [klauspost/reedsolomon#76]
# github.com/klauspost/reedsolomon
klauspost/reedsolomon/galois_amd64.s:146: unrecognized instruction "VINSERTI128"
klauspost/reedsolomon/galois_amd64.s:147: unrecognized instruction "VINSERTI128"
klauspost/reedsolomon/galois_amd64.s:159: unrecognized instruction "VPSRLQ"
klauspost/reedsolomon/galois_amd64.s:162: unrecognized instruction "VPSHUFB"
klauspost/reedsolomon/galois_amd64.s:163: unrecognized instruction "VPSHUFB"
klauspost/reedsolomon/galois_amd64.s:187: unrecognized instruction "VINSERTI128"
klauspost/reedsolomon/galois_amd64.s:188: unrecognized instruction "VINSERTI128"
klauspost/reedsolomon/galois_amd64.s:199: unrecognized instruction "VPSRLQ"
klauspost/reedsolomon/galois_amd64.s:202: unrecognized instruction "VPSHUFB"
klauspost/reedsolomon/galois_amd64.s:203: unrecognized instruction "VPSHUFB"
asm: asm: assembly of klauspost/reedsolomon/galois_amd64.s failed

**Comment by klauspost** [comment]
You probably need a newer Go installation. These should be supported from Go 1.7 and upwards, maybe even 1.6. Current release is Go 1.9.

**Comment by klauspost** [comment]
You can also pull [v1.6](https://github.com/klauspost/reedsolomon/releases/tag/v1.6), which is compatible back to Go 1.5 or thereabout.

**Comment by Hoke** [comment]
thank you，before my go version is go1.6.2 linux/amd64
