### ISSUE TITLE
how to deal with partially overwriting

### ISSUE THREAD

**Issue by vtolstov** [klauspost/reedsolomon#77]
I'm check examples but have no luck.
I have for example 4Mb of data and want to use this package to split it for 1Mb data blocks and add parity to it. After that i need to overwrite this 4Mb of data from 2Mb and to 3Mb (1Mb of data).
I know that i can read back 4Mb of data, modify it and write again, but this is significant overhead in case of massive read/write. How to deal in this case and not re-read again all data block?

**Comment by darrenldl** [comment]
So you essentially have 4x1Mb data blocks, and you want to add some number of parity blocks to it.

Then you want to overwrite the 3rd data block with some other data?

And why do you need to read all 4x1Mb data blocks again to modify and write again? Is this due to the medium(e.g. disk, network)?

**Comment by vtolstov** [comment]
Ok, i'm retry =). Main question - how to deal if i need overwrite data that belongs to 2 blocks (for example last 512Kb on one block and first 512K of another.

**Comment by darrenldl** [comment]
I am guessing you're asking about error detection and recovery then?

For error detection, you can supply the parity shards(at least 1 parity shard) and use the `Verify` method, but this does not tell which blocks are overwritten/corrupted, it only tells if there are some blocks that are corrupted.

To know which specific blocks are overwritten/corrupted, you need to use checksum(e.g. CRC16, CRC32, SHA256, SHA512).

For error correction, you need to first know which blocks are not usable, then change them to `nil` and use the `Reconstruct` method.

For memory overhead in above case, you need to load all existing blocks(data + parity blocks) into memory in order to recover the errors.

**Comment by vtolstov** [comment]
Thanks, so as i understand if i have blocks 16Mb and i need to overwrite 1Mb of data i need always reread 16Mb to modify 1Mb in memory and write it again to disk?

**Comment by darrenldl** [comment]
I am slightly lost on your exact configuration(sorry!), so I will list both situations below.

#### Situation A
You have **M** data shards/blocks, and **N** parity shards/blocks.

**Each shard/block is 16Mb in size.**

1Mb **of** a block is overwritten/corrupted. To repair the block, you do not need to load the block anymore(just pretend it is missing), but you need to load at least **M** blocks. The **M** blocks can be data blocks or parity blocks.

This means you need at least **16Mb * M** space available in memory for storing blocks.

`Reconstruct` will simply recreate the broken block in memory, and you just write it back to disk. The library does not restrict how you manage your blocks, so in our case, we need to read at least **16Mb * M**, , we need to write 1 block(16Mb).

#### Situation B
You have **M** data shards/blocks, and **N** parity shards/blocks, and **M + N** = 16 (16 blocks in total).

**Each shard/block is 1Mb in size.**

A block is overwritten/missing/corrupted. To repair the block, you do not need to load the block anymore(just pretend it is missing), but you need to load at least **M** blocks. The **M** blocks can be data blocks or parity blocks.

This means you need at least **1Mb * M** space available in memory for storing blocks.

`Reconstruct` will simply recreate the broken block in memory, and you just write it back to disk. The library does not restrict how you manage your blocks, so in our case, we need to read at least **1Mb * M**, and we need to write 1 block(1Mb).

#### Notes
The memory requirement largely depends on the block size you cut your data in. Note that with higher number of blocks, even at same ratio, you get lower performance i.e. `10 Data + 2 Parity` is faster than `100 Data + 20 Parity`. The latter is more flexible and can shrink the potential memory needed, but it is also much slower.

The performance also drops significantly if your block size is too small, e.g. 100b is much, much slower than 16Mb.

#### Extra notes
I am not entirely sure if erasure code is what you're looking for. Erasure code deals with data in blocks, and does not handle error detection. This also means everything is aligned to block size, e.g. if you have error that spreads across 2 blocks, you always need to recreate both blocks. So even if you only have a error of 1bit/byte, you still need to recreate the entire 16Mb block.

Other forward error correction codes that are not erasure codes can deal with data in bits or bytes, and can handle error detection and correction, and also erasures. This means you don't deal with error in blocks, but in bits/bytes, so you never need to dump an entire block just to repair a very small error, you just detect that bit/byte and repair it.

This library implements Reed-Solomon erasure codes only, Reed-Solomon code that is not erasure code would look more like [this](https://www.cs.cmu.edu/~guyb/realworld/reedsolomon/reed_solomon_codes.html), more stream oriented if you will.

**Comment by klauspost** [comment]
Thanks for the great explanation @darrenldl 

Closing the issue for now.

**Comment by vtolstov** [comment]
Thanks
