### ISSUE TITLE
Question: is it mandatory to call Verify after Encode?

### ISSUE THREAD

**Issue by vitalyisaev2** [klauspost/reedsolomon#82]
In the [basic example](https://godoc.org/github.com/klauspost/reedsolomon#example-Encoder) `encoder.Verify` is called twice: both after `Encode` and `Reconstruct` actions. It's clear why we have to verify shards after reconstruction, but do we need to verify `Encode` operation as well?

Kind regards,
Vitaly

**Comment by klauspost** [comment]
No it is purely for demonstration purposes. Calling after Reconstruct is also optional and should not give failures.

**Comment by vitalyisaev2** [comment]
Thank you! I had doubts about these functions, so now going to avoid it for perfomance reasons.

**Comment by vitalyisaev2** [comment]
Thank you, because I had doubt about this function, but now I feel free to delete it from the code (for the
