### ISSUE TITLE
Optimization for power 

### ISSUE THREAD

**Issue by ghatwala** [klauspost/reedsolomon#84]
Hi @klauspost ,

I have been trying to understand the process for creating optimized go code for power(ppc64le) in here "https://github.com/klauspost/reedsolomon" similar to the optimization done for amd(galois_amd64.go) and arm(galois_arm64.go).

My understanding is below for example on "amd64"
The routines that have been optimized for amd64 and are present in " galois_amd64.go" in klauspost repo.
o galMulSlice
o galMulSliceXor
o sliceXor
The un-optimized implementation of the above routines is in "galois_noasm.go " and this would be the one that is getting invoked for Power currently. ? 

To implement the equivalent power assembly  - which intel equivalent needs to be considered - AVX2 or  SSSE3 ?

**Comment by fwessels** [comment]
This has been fixed with https://github.com/klauspost/reedsolomon/pull/88

**Comment by klauspost** [comment]
Indeed!
