### ISSUE TITLE
Issue with odd number of shards

### ISSUE THREAD

**Issue by niteshemmadi** [klauspost/reedsolomon#85]
Facing problem with reconstructing file while using odd number of data shards(5,2):
var dataShards = flag.Int("data", 5, "Number of shards to split the data into, must be below 257.")
var parShards = flag.Int("par", 2, "Number of parity shards")

My terminal output:
----------------------------------------------------------------------------------------------------------------------------------
$ ./simple-encoder README.md 
Opening README.md
File split into 7 data+parity shards with 287 bytes/shard.
Writing to README.md.0
Writing to README.md.1
Writing to README.md.2
Writing to README.md.3
Writing to README.md.4
Writing to README.md.5
Writing to README.md.6

$ rm README.md.0 README.md.1

$ mv README.md README.md.bkp
$ rm -rf README.md

$./simple-decoder README.md
Opening README.md.0
Error reading file open README.md.0: no such file or directory
Opening README.md.1
Error reading file open README.md.1: no such file or directory
Opening README.md.2
Opening README.md.3
Opening README.md.4
Opening README.md.5
Opening README.md.6
Verification failed. Reconstructing data
Writing data to README.md

$ sha1sum README.md README.md.bkp 
a1376818a75bdb3daa925eb84787deaea08f70a3  README.md
16bcbf011764251da257a7ab39b7cdc02395748d  README.md.bkp

--------------------------------------------------------------------------------------------------------------------------------
Newly constructed files includes control characters "^@^@^@"

Please suggest how to solve this.

**Comment by klauspost** [comment]
Hi!

The "simple-encoder" has some limitations [listed in the source](https://github.com/klauspost/reedsolomon/blob/master/examples/simple-encoder.go#L15). The important one is the first:

> If the file size of the input isn't (divisible) by the number of data shards the output will contain extra zeroes.

The solution for this is listed below and requires you to store the expected output size somewhere else, (along with a hash for each shard for checking whether a shard is good).

**Comment by niteshemmadi** [comment]
Sure. Storing and verifying hash of each shard separately works for my system. Thanks.
