### ISSUE TITLE
Is it identical to call Reconstruct() instead of Encode()?

### ISSUE THREAD

**Issue by TennyZhuang** [klauspost/reedsolomon#99]
If l always call Reconstruct([datas..., nil, nil, nil], [nil, nil, nil, parities...]) instead of call Encode(datas, parities), is it identical in both result and performance?

**Comment by templexxx** [comment]
@TennyZhuang 
In theory, yes. But need more time for searching matrix(although it's just the generator matrix) and allocating memory space.

**Comment by TennyZhuang** [comment]
In my opinion, the additional memory and time is O(n*m) and is not related to data, so the additional cost can be ignored for large data (such as 1GB or more), is it right?

**Comment by templexxx** [comment]
Yes. The cost is not expensive

**Comment by TennyZhuang** [comment]
Thanks
